# Generated by Django 4.2.3 on 2025-04-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_post_image_post_likes_post_summary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='post',
            name='reading_time',
            field=models.PositiveIntegerField(default=3, help_text='Estimated reading time in minutes'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar_color',
            field=models.CharField(default='#4e73df', help_text='Hex color code for avatar background', max_length=7),
        ),
    ]
